version: "3.8"

secrets:
  privkey:
    file: './secrets/ssl/privkey.pem'
  cert:
    file: './secrets/ssl/fullchain.pem'
  s3endpoint:
    file: './secrets/s3endpoint.txt'
  s3accessKey:
    file: './secrets/s3accessKey.txt'
  s3secretKey:
    file: './secrets/s3secretKey.txt'
services:
  api:
    image: joshuamshana/bfast-ee:v0.5.36-alpha.0
    hostname: bfast
    restart: always
    networks:
      - bfastweb
      - default
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - "traefik.docker.network=bfastweb"
    environment:
      - MONGO_URL=mongodb://fahamutechdb:fahamutechm0ng0db@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/_BFAST_ADMIN?authSource=admin&replicaSet=mdbRepl
    deploy:
      labels:
        - traefik.docker.network=bfastweb
        - traefik.enable=true
        - traefik.http.routers.r0.rule=Host(`api.bfast.fahamutech.com`)
        - traefik.http.routers.r0.entrypoints=websecure
        - traefik.http.services.s0.loadbalancer.server.port=3000
        - traefik.http.services.s0.loadbalancer.server.scheme=http
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 2s
  rdb:
    image: redis:5-alpine
    hostname: rdb
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      placement:
        constraints: [node.role == manager]
    networks:
      - bfastweb
      - default
    volumes:
      - redisdata:/data
    command:
      - --appendonly yes
  traefik:
    image: traefik:v2.2
    hostname: traefik
    working_dir: /app
    restart: always
    secrets:
      - privkey
      - cert
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443
    networks:
      - bfastweb
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/:/app/traefik/"
    command:
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      #- --entrypoints.web.http.redirections.entryPoint.to=websecure
      #- --entrypoints.web.http.redirections.entryPoint.scheme=https
      # - --retry
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=bfastweb
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.watch=true
      - --providers.file.watch=true
      - --providers.file.directory=/app/traefik/
      - --providers.docker.exposedbydefault=false
volumes:
  traefikdata:
  redisdata:
  mongodatars2:
  mongodatars1:
  mdbdata:
networks:
  bfastweb:
    external: true
