version: "3.8"

secrets:
  privkey:
    file: './secrets/ssl/privkey.pem'
  cert:
    file: './secrets/ssl/fullchain.pem'
  s3endpoint:
    external: true
  s3endpointUsEast1:
    external: true
  s3accessKey:
    external: true
  s3secretKey:
    external: true
services:
  api:
    image: joshuamshana/bfast-ee:v0.5.37-alpha.1
    hostname: bfast
    restart: always
    networks:
      - bfastweb
      - default
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - "traefik.docker.network=bfastweb"
    environment:
      - MONGO_URL=mongodb://fahamutechdb:fahamutechm0ng0db@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/_BFAST_ADMIN?authSource=admin&replicaSet=mdbRepl
    deploy:
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:api.bfast.fahamutech.com"
        - "traefik.port=3000"
        - "traefik.protocol=http"
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 2s
  rdb:
    image: redis:5-alpine
    hostname: rdb
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      placement:
        constraints: [node.role == manager]
    networks:
      - bfastweb
      - default
    volumes:
      - redisdata:/data
    command:
      - --appendonly yes
  traefik:
    image: traefik:v1.7
    hostname: traefik
    working_dir: /app
    restart: always
    secrets:
      - privkey
      - cert
    deploy:
      restart_policy:
        condition: any
        delay: 2s
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443
    networks:
      - bfastweb
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/acme.json:/app/acme.json"
    command:
      #      - --logLevel=ERROR
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS:/run/secrets/cert,/run/secrets/privkey
      - --retry
      - --docker
      - --docker.swarmMode
      - --docker.network=bfastweb
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=api.bfast.fahamutech.com
      - --docker.watch=true
      - --docker.exposedbydefault=false
      - --retry
volumes:
  traefikdata:
  redisdata:
  mongodatars2:
  mongodatars1:
  mdbdata:
networks:
  bfastweb:
    external: true
