version: "3.3"

services:
  bfastapp:
    image: joshuamshana/bfastcoreadmin
    hostname: bfastapp
    restart: always
    networks: 
      - bfastweb
      - default
    ports:
      - 3000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels: 
      - "traefik.docker.network=bfastweb"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:cloud.bfast.fahamutech.com"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      # - "traefik.admin.frontend.rule=Host:admin-app.my-awesome-app.org"
      # - "traefik.admin.protocol=https"
      # - "traefik.admin.port=9443"
    deploy:
      placement:
        constraints: [node.role == manager]
  mdb:
    image: mongo:4-bionic
    hostname: mdb
    restart: always
    volumes:
      - 'mdbdata:/data/db'
    networks: 
      - default
    deploy:
      placement:
        constraints: [node.role == manager]
  traefik:
    image: traefik:v1.7
    hostname: traefik
    # container_name: "traefik"
    working_dir: /app
    restart: always
    ports:
      - 81:80
      - 443:443
    networks:
      - bfastweb
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./traefik.toml:/traefik.toml
      - traefikdata:/app/
    deploy:
      placement:
        constraints: [node.role == manager]
    command: 
      # - "--api.insecure=true"
      # - "--providers.docker=true"
      - "--debug=true"
      - "--logLevel=DEBUG"
      - "--defaultentrypoints=https,http" #https
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--retry"
      - "--docker.endpoint=unix:///var/run/docker.sock"
      - "--docker.domain=*.bfast.fahamutech.com"
      - "--docker.watch=true"
      - "--docker.exposedbydefault=false"
      - "--acme.email=mama27j@gmail.com"
      - "--acme.storage=/app/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onHostRule=true"
      - "--acme.httpchallenge.entrypoint=http"
volumes:
  mdbdata:
  traefikdata:
networks:
  bfastweb:
    external: true
