version: "3"

services:
  bfastapp:
    build: ./
    hostname: bfastapp
    restart: always
    ports:
      - 3000
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  mdb:
    image: mongo
    hostname: mdb
    restart: always
    volumes:
      - 'mdbdata:/data/db'
volumes:
  mdbdata:
