version: '3.3'
services:
  daas:
    image: parseplatform/parse-server:3.9.0
    hostname: ${projectId}_daas
    restart: always
    networks:
      - default
      - bfastweb # to access mdb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 256M
      labels:
      - "traefik.docker.network=bfastweb"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${projectId}_daas.bfast.fahamutech.com"
      # - "traefik.backend=${projectId}_daas"
      # - "traefik.backend.rule=PathPrefix:/parse"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    environment:
      - PARSE_SERVER_APPLICATION_ID=${appId}
      - PARSE_SERVER_MASTER_KEY=${masterKey}
      # - PARSE_SERVER_URL=http://localhost:3000
      - PARSE_SERVER_DATABASE_URI=mongodb://mdb:27017/${projectId}
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY={"classNames":[]}
      - PARSE_SERVER_MAX_UPLOAD_SIZE=1048576mb
      - PARSE_SERVER_OBJECT_ID_SIZE=15
      - PARSE_SERVER_SCHEMA_CACHE_TTL=10000
      - PORT=3000
      - PARSE_SERVER_MOUNT_PATH=/
  dashboard:
    image: parseplatform/parse-dashboard:2.0.3
    hostname: ${projectId}_dashboard
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          # cpus: '0.50'
          memory: 256M
        # reservations:
        #   cpus: '0.25'
        #   memory: 20M
      labels:
      - "traefik.docker.network=bfastweb"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${projectId}.bfast.fahamutech.com"
      # - "traefik.backend=${projectId}_dashboard"
      - "traefik.port=3443"
      - "traefik.protocol=http"
    environment:
      - PORT=3443
      - PARSE_DASHBOARD_SERVER_URL=https://${projectId}_daas.bfast.fahamutech.com
      - PARSE_DASHBOARD_APP_ID=${appId}
      - PARSE_DASHBOARD_MASTER_KEY=${masterKey}
      - PARSE_DASHBOARD_APP_NAME=${projectName}
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=0
      - PARSE_DASHBOARD_USER_ID=${userEmail}
      - PARSE_DASHBOARD_USER_PASSWORD=${masterKey}
  faas:
    image: joshuamshana/bfastfaas:v1.4.10
    hostname: ${projectId}_faas
    restart: always
    volumes:
    - faasdata:/faas/src/function
    networks:
      - default
      - bfastweb # to access mdb
    deploy:
      resources:
        limits:
          # cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: any
        delay: 2s
        # max_attempts: 3
        # window: 120s
      labels:
      - "traefik.docker.network=bfastweb"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${projectId}_faas.bfast.fahamutech.com"
      # - "traefik.backend=${projectId}_faas"
      # - "traefik.backend.rule=PathPrefix:/faas"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - PROJECT_ID=${projectId}
networks:
  bfastweb:
    # driver: overlay
    # attachable: true
    external: true
volumes:
  daasdata: {}
  faasdata: {}
  webdata: {}
