version: '3.3'
services:
  ide:
    image: joshuamshana/bfastcore
    hostname: ide
    volumes:
    - idedata:/ide/src/spring
    - mongodata:/ide/mongo/data:ro
    networks:
      - default
    restart: always
    depends_on: 
      - mdb
      - web
      - faas
  web:
    image: joshuamshana/bfastnginx
    hostname: web
    labels: 
      - "traefik.docker.network=bfastweb"
    deploy:
      labels: 
      - "traefik.docker.network=bfastweb"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${projectId}.bfast.fahamutech.com"
      - "traefik.port=80"
      - "traefik.protocol=http"
      # - "traefik.admin.frontend.rule=Host:admin-app.my-awesome-app.org"
      # - "traefik.admin.protocol=https"
      # - "traefik.admin.port=9443"
    networks:
      - bfastweb
      - default
    expose:
    - "80" # replace ports with your own
    restart: always
  mdb:
    image: joshuamshana/bfastmdb
    hostname: mdb
    volumes:
    - mongodata:/data/db
    restart: always
    networks:
      - default
    depends_on: 
      - mdbrs1
      - mdbrs2
  mdbrs1:
    image: mongo:4-bionic
    hostname: mdbrs1
    volumes:
    - mongodatars1:/data/db
    networks:
      - default
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "lrs" ]
  mdbrs2:
    image: mongo:4-bionic
    hostname: mdbrs2
    volumes:
    - mongodatars2:/data/db
    networks:
      - default
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "lrs" ]
  daas:
    image: joshuamshana/bfastdaas
    hostname: daas
    restart: always
    volumes:
    # - daasdata:/app
    - idedata:/ide:ro
    networks:
      - default
  faas:
    image: joshuamshana/bfastfaas
    hostname: faas
    restart: always
    volumes: 
    - faasdata:/faas
    networks:
      - default
networks:
  bfastweb:
    # driver: overlay
    # attachable: true
    external: true
volumes: 
  idedata: {}
  mongodata: {}
  mongodatars1: {}
  mongodatars2: {}
  daasdata: {}
  faasdata: {}
  webdata: {}