version: '3.3'
services:
  daas:
    image: parseplatform/parse-server:3.10.0
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 125M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-daas.bfast.fahamutech.com"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - PARSE_SERVER_APPLICATION_ID=${appId}
      - PARSE_SERVER_MASTER_KEY=${masterKey}
      - PARSE_SERVER_DATABASE_URI=mongodb://mdb:27017,mdbrs1:27017,mdbrs2:27017/${projectId}?replicaSet=bfastRS
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY={"classNames":[]}
      - PARSE_SERVER_MAX_UPLOAD_SIZE=1048576mb
      - PARSE_SERVER_OBJECT_ID_SIZE=16
      - PARSE_SERVER_SCHEMA_CACHE_TTL=10000
      - PORT=3000
      - PARSE_SERVER_MOUNT_PATH=/
  dashboard:
    image: parseplatform/parse-dashboard:2.0.3
    hostname: ${projectId}-dashboard
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 80M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}.bfast.fahamutech.com"
        - "traefik.port=3443"
        - "traefik.protocol=http"
    environment:
      - PORT=3443
      - PARSE_DASHBOARD_SERVER_URL=https://${projectId}-daas.bfast.fahamutech.com
      - PARSE_DASHBOARD_APP_ID=${appId}
      - PARSE_DASHBOARD_MASTER_KEY=${masterKey}
      - PARSE_DASHBOARD_APP_NAME=${projectName}
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=0
      - PARSE_DASHBOARD_USER_ID=${userEmail}
      - PARSE_DASHBOARD_USER_PASSWORD=${masterKey}
  faas:
    image: joshuamshana/bfastfaas:v1.8.0
    hostname: ${projectId}-faas
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 0
      resources:
        limits:
          memory: 125M
      restart_policy:
        condition: any
        delay: 2s
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-faas.bfast.fahamutech.com"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://mdb:27017,mdbrs1:27017,mdbrs2:27017/${projectId}?replicaSet=bfastRS
networks:
  bfastweb:
    external: true
volumes:
  daasdata: {}
  faasdata: {}
  webdata: {}
