version: '3.8'
secrets:
  s3endpoint:
    external: true
  s3endpointUsEast1:
    external: true
  s3accessKey:
    external: true
  s3secretKey:
    external: true
services:
  daas:
    image: joshuamshana/bfastfunction:latest
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    secrets:
      - s3endpoint
      - s3endpointUsEast1
      - s3accessKey
      - s3secretKey
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-daas.${cluster}.${hostDomain}"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - MASTER_KEY=${masterKey}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PORT=3000
      - GIT_USERNAME=joshuamshana
      - GIT_CLONE_URL=https://github.com/fahamutech/bfast-database.git
      - MODE=npm
      - NPM_TAR=bfast-database
      - PRODUCTION=1
      - MOUNT_PATH=/
      - S3_BUCKET=${cluster}-${bucketName}
      - S3_ACCESS_KEY=/run/secrets/s3accessKey
      - S3_SECRET_KEY=/run/secrets/s3secretKey
      - S3_ENDPOINT=/run/secrets/s3endpointUsEast1
  faas:
    image: joshuamshana/bfastfunction:latest
    hostname: ${projectId}-faas
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: any
        delay: 2s
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-faas.${cluster}.${hostDomain}"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PORT=3000
      - PRODUCTION=1
networks:
  bfastweb:
    external: true
