version: '3.8'
services:
  daas:
    image: joshuamshana/bfast-ce-daas:latest
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    secrets:
      - s3endpoint.secret.txt
      - s3accessKey.secret.txt
      - s3secretKey.secret.txt
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 125M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.http.routers.router0.rule=Host(`${projectId}-daas.bfast.fahamutech.com`) "
        #        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - MASTER_KEY=${masterKey}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PORT=3000
      - MOUNT_PATH=/
      - S3_BUCKET=daas-${bucketName}
      - S3_ACCESS_KEY=/run/secrets/s3accessKey.secret.txt
      - S3_SECRET_KEY=/run/secrets/s3secretKey.secret.txt
      - S3_ENDPOINT=/run/secrets/s3endpoint.secret.txt
networks:
  bfastweb:
    external: true
