version: '3.8'
services:
  ssm:
    image: joshuamshana/bfast-ce-daas:latest
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 125M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-daas.bfast.fahamutech.com"
#        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - MASTER_KEY=${masterKey}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PORT=3000
      - MOUNT_PATH=/
      - S3_BUCKET=smartstock-${bucketName}
      - S3_ACCESS_KEY=5IGXSX5CU52C2RFZFALG
      - S3_SECRET_KEY=2q2vteO9lQp6LaxT3lGMLdkUF5THdxZWmyWmb1y9
      - S3_ENDPOINT=https://eu-central-1.linodeobjects.com/
networks:
  bfastweb:
    external: true
