version: '3.7'
services:
  ssm:
    image: joshuamshana/bfast-ce-daas
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 125M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-daas.bfast.fahamutech.com"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - PARSE_SERVER_APPLICATION_ID=${appId}
      - PARSE_SERVER_MASTER_KEY=${masterKey}
      - PROJECT_ID=${projectId}
      - PARSE_SERVER_DATABASE_URI=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      - PARSE_SERVER_LIVE_QUERY={"classNames":["stocks","sales","purchases","units","categories","accounts","suppliers","orders"]}
      - PARSE_SERVER_MAX_UPLOAD_SIZE=1048576mb
      - PARSE_SERVER_OBJECT_ID_SIZE=16
      - PARSE_SERVER_SCHEMA_CACHE_TTL=10000
      - PORT=3000
      - PARSE_SERVER_MOUNT_PATH=/
      - S3_BUCKET=smartstock-${bucketName}
      - S3_ACCESS_KEY=5IGXSX5CU52C2RFZFALG
      - S3_SECRET_KEY=2q2vteO9lQp6LaxT3lGMLdkUF5THdxZWmyWmb1y9
      - S3_ENDPOINT=https://eu-central-1.linodeobjects.com/
networks:
  bfastweb:
    external: true