version: '3.8'
secrets:
  bfast_s3endpoint:
    external: true
  bfast_s3accessKey:
    external: true
  bfast_s3secretKey:
    external: true
services:
  daas:
    image: joshuamshana/bfast-ce-daas:latest
    hostname: ${projectId}-daas
    restart: always
    networks:
      - default
      - bfastweb
    secrets:
      - bfast_s3endpoint
      - bfast_s3accessKey
      - bfast_s3secretKey
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 2s
      resources:
        limits:
          memory: 125M
      labels:
        - "traefik.docker.network=bfastweb"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:${projectId}-daas.bfast.fahamutech.com"
        # - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.port=3000"
        - "traefik.protocol=http"
    environment:
      - APPLICATION_ID=${appId}
      - MASTER_KEY=${masterKey}
      - PROJECT_ID=${projectId}
      - MONGO_URL=mongodb://${appId}:${masterKey}@1.mongo.fahamutech.com:27017,2.mongo.fahamutech.com:27017,3.mongo.fahamutech.com:27017/${projectId}?authSource=admin&replicaSet=mdbRepl
      - PORT=3000
      - MOUNT_PATH=/
      - S3_BUCKET=smartstock-${bucketName}
      - S3_ACCESS_KEY=/run/secrets/bfast_s3accessKey
      - S3_SECRET_KEY=/run/secrets/bfast_s3secretKey
      - S3_ENDPOINT=/run/secrets/bfast_s3endpoint
networks:
  bfastweb:
    external: true
