name: Build and publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongo docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: install, build, test and publish
        run: |
          npm install -g yarn
          yarn install
          npm publish
#          npm install -g ipfs
#          jsipfs init
#          jsipfs config --json Addresses.API '["/ip4/127.0.0.1/tcp/5001"]'
#          jsipfs daemon &
#          sleep 15s
#          yarn test
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

# npm install --production
# npm publish --registry https://registry.npmjs.org/:_authToken=${NPM_TOKEN}
